# -*- coding: utf-8 -*-
"""FIFA WORLD CUP ANALYSIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13LQyeh1q0g1-qIl-l-MiZODxUpCP433j

## FIFA WORLD CUP ANALYSIS
"""

# Importing the dependencies
import pandas as pd
import numpy as np

# Loading the Dataset
worldcup_matches = pd.read_csv('/content/WorldCupMatches.csv')
worldcup_players = pd.read_csv('/content/WorldCupPlayers.csv')
worldcup_info = pd.read_csv('/content/WorldCups.csv')

worldcup_matches.head()

worldcup_players.head()

worldcup_info.head()

# Data Integration: Merging Dataset
merged_data = pd.merge(worldcup_matches, worldcup_players, on = ['RoundID', 'MatchID'])
merged_data = pd.merge(merged_data, worldcup_info, on = 'Year')

# Checking the info the merged dataset
merged_data.info()

# Checking missing value
merged_data.isnull().sum()

# Dropping irrelevant columns and null values
merged_data.dropna(inplace = True)

merged_data.isnull().sum()

merged_data.describe()

# Exporting merged data to CSV
merged_data.to_csv('merged_data.csv', index = False)