# -*- coding: utf-8 -*-
"""Analyzing_Amazon_Sales_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dvkrRcDyBCf0pEQ9AucX3tOmHIufN8iJ

# Analyzing Amazon Sales Data
"""

# IMPORTING THE DEPENDENCIES
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Loading the Dataset
amazonData = pd.read_csv('/content/Amazon Sales data.csv')

# Displaying top 5 rows of the dataset
amazonData.head()

# Checking info of the dataset
amazonData.info()

# Checking the null values
amazonData.isnull().sum()

# Statistical measures
amazonData.describe()

"""### OBSERVATION


- **Order ID**: The order IDs range widely, indicating a diverse set of orders. The mean order ID suggests a relatively balanced distribution across the dataset.

- **Units Sold**: The average number of units sold per order is around 5129, with a considerable standard deviation, indicating variability in order sizes.

- **Unit Price and Unit Cost**: The unit price and cost exhibit considerable variability, with unit prices generally higher than unit costs, as expected. The difference between unit price and cost contributes to the profit margin.

- **Total Revenue, Total Cost, and Total Profit**: The total revenue, cost, and profit figures vary significantly across orders, with substantial standard deviations indicating variability in sales performance. Despite this variability, the mean total profit suggests a healthy overall profit margin.

Overall, the summary statistics indicate a dynamic sales environment with a range of order sizes, pricing strategies, and profit margins.
"""

# Extracting month and year from the 'Order Date' column
amazonData['Order Date'] = pd.to_datetime(amazonData['Order Date'])
amazonData['Month'] = amazonData['Order Date'].dt.month
amazonData['Year'] = amazonData['Order Date'].dt.year

# Sales trend analysis: Month-wise
monthly_sales = amazonData.groupby('Month')['Total Revenue'].sum()
monthly_sales.plot(kind = 'bar', color = 'skyblue')
plt.title('Month-wise Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Revenue')

# Sales trend analysis: Year-wise
yearly_sales = amazonData.groupby('Year')['Total Revenue'].sum()
yearly_sales.plot(kind = 'bar', color = 'salmon')
plt.title('Year-wise Sales Trend')
plt.xlabel('Year')
plt.ylabel('Total Revenue')

# Sales trend analysis: Monthly and Year-wise
year_month_sales = amazonData.groupby(['Month', 'Year'])['Total Revenue'].sum()
year_month_sales.unstack().plot(kind = 'line', marker = 'o', figsize = (15, 6))
plt.title('Yearly Month-wise Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Revenue')
plt.legend(title = 'Year')

"""Key Metrics"""

total_revenue = amazonData['Total Revenue'].sum()
total_cost = amazonData['Total Cost'].sum()
total_profit = amazonData['Total Profit'].sum()
average_revenue_per_order = amazonData['Total Revenue'].mean()

print("Key Metrics:")
print("Total Revenue:", total_revenue)
print("Total Cost:", total_cost)
print("Total Profit:", total_profit)
print("Average Revenue per Order:", average_revenue_per_order)

"""Factors Analysis"""

# Numerical Attributes vs 'Total Revenue', 'Total Cost', 'Total Profit'
numerical_attributes = ['Unit Price', 'Unit Cost', 'Units Sold']
correlation_matrix = amazonData[numerical_attributes + ['Total Revenue', 'Total Cost', 'Total Profit']].corr()

sb.heatmap(correlation_matrix, annot = True, cmap = 'coolwarm', fmt = ".2f", linewidths = 0.5)
plt.title('Correlation Matrix between Numerical Attributes and Key Metrics')
plt.show()

"""### OBSERVATION

- Unit price has a strong positive correlation with total revenue and total profit. This means that as the unit price increases, total revenue and total profit also tend to increase.
- Unit cost has a strong positive correlation with total cost. This means that as the unit cost increases, the total cost also tends to increase. This is intuitive, as the total cost is calculated by multiplying the unit cost by the number of units sold.
- Units sold has a weak positive correlation with total revenue and total profit. This means that there is a slight tendency for total revenue and total profit to increase as the number of units sold increases. However, the correlation is weak, so this relationship is not very strong.
- There is no correlation between units sold and unit price or unit cost. This means that there is no relationship between the number of units sold and the unit price or unit cost.
"""

# Categorical Attributes vs 'Total Revenue'
categorical_attributes = ['Region', 'Item Type', 'Sales Channel', 'Order Priority']
plt.figure(figsize = (15, 10))
for i, attribute in enumerate(categorical_attributes, 1):
    plt.subplot(2, 3, i)
    sb.boxplot(x = attribute, y = 'Total Revenue', data = amazonData)
    plt.title(attribute + ' vs. Total Revenue')
    plt.xticks(rotation = 90)

plt.tight_layout()
plt.show()

"""### OBSERVATION

- Based on the box plots, it is possible to infer that the total revenue of a company is higher in some areas than in others. For example, the box plot for North America shows a higher median and upper quartile than the box plots for most other regions. This means that the center of the data (median) and the upper half of the data (upper quartile) for North America are higher than those for most other regions.

- Similarly, the box plot for Online sales channel shows a higher median and upper quartile than the box plot for Offline sales channel. This suggests that the company makes more revenue through online channels than offline channels.
"""

# Categorical Attributes vs 'Total Cost'
categorical_attributes = ['Region', 'Item Type', 'Sales Channel', 'Order Priority']
plt.figure(figsize = (15, 10))
for i, attribute in enumerate(categorical_attributes, 1):
    plt.subplot(2, 3, i)
    sb.boxplot(x = attribute, y = 'Total Cost', data = amazonData)
    plt.title(attribute + ' vs. Total Cost')
    plt.xticks(rotation = 90)

plt.tight_layout()
plt.show()

"""### OBSERVATION

- There is a positive correlation between the region and the total cost of a product. This means that products tend to be more expensive in some regions than others.
- North America and Europe appear to be the two regions with the highest total costs.
- Central America and the Caribbean and Sub-Saharan Africa appear to be the two regions with the lowest total costs.
"""

# Categorical Attributes vs 'Total Profit'
categorical_attributes = ['Region', 'Item Type', 'Sales Channel', 'Order Priority']
plt.figure(figsize = (15, 10))
for i, attribute in enumerate(categorical_attributes, 1):
    plt.subplot(2, 3, i)
    sb.boxplot(x = attribute, y = 'Total Profit', data = amazonData)
    plt.title(attribute + ' vs. Total Profit')
    plt.xticks(rotation = 90)

plt.tight_layout()
plt.show()

"""### OBSERVATION

- Based on the box plots, it is possible to infer that there is a positive correlation between the order priority and the total profit. This is because the median and upper quartile of the total profit for orders with higher priority is higher than the median and upper quartile of the total profit for orders with lower priority.

- For example, the median total profit for orders with "High" priority is around $1,500,000, while the median total profit for orders with "Low" priority is around $750,000. This suggests that orders with higher priority tend to have higher total profits.
"""

# Exporting the final data for creating tableau dashboard
amazonData.to_csv("my_data.csv", index = False)

"""## FINDINGS

1. **Sales Trends**:
   - Month-wise analysis reveals fluctuating sales throughout the year, with some months performing better than others.
   - Year-wise analysis shows variations in total revenue over different years, indicating potential seasonal or market changes.

2. **Key Metrics**:
   - Total revenue, total cost, and total profit figures are significant, indicating a robust sales operation.
   - Average revenue per order provides insight into the typical value of each transaction.

3. **Factors Analysis**:
   - Unit price exhibits a strong positive correlation with total revenue and total profit, suggesting that higher prices contribute to increased revenue and profit.
   - Unit cost correlates strongly with total cost, indicating that higher costs impact overall expenses.
   - Units sold show a weak positive correlation with total revenue and total profit, suggesting a slight increase in revenue and profit with higher sales volume.

4. **Categorical Attributes Analysis**:
   - Total revenue varies across different regions and sales channels, with North America and online channels generally yielding higher revenues.
   - Total cost also varies across regions, with North America and Europe having higher costs.
   - Order priority correlates positively with total profit, indicating that higher priority orders tend to generate more profit.
"""