# -*- coding: utf-8 -*-
"""HeartDiseaseDiagnosticAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KHOd0oAYMinrVUq2WLWuyotlMr8oHCRe

# Heart Disease Diagnostic Analysis
"""

# Commented out IPython magic to ensure Python compatibility.
# Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
# %matplotlib inline
import warnings
warnings.filterwarnings("ignore")

# Display all the columns of dataframe
pd.pandas.set_option('display.max_columns', None)

# loading the dataset
df = pd.read_csv("/content/Heart Disease data.csv")

# Shape of the dataset with rows and columns
df.shape

# Displaying the first 5 rows of dataset
df.head()

# Checking the info of the dataset
df.info()

# Checking the missing values
df.isnull().sum()

"""### OBSERVATION
- There is no missing value in any of the column.
"""

# Statistical Information
df.describe()

# Creating a function to convert numerical feature to categorical feature
def heart_diseases(value):
    if value == 0:
        return 'presence'
    else:
        return 'absence'

# Adding a new column to the dataset of converted data
df['heart_disease'] = df['target'].apply(heart_diseases)

df.head()

# Counting the number of people having heart diseases and not having heart disease
hd = df.groupby('heart_disease')['target'].count()
hd

# Ploting the bar chart of people having and not having heart disease
clrs = sb.color_palette('bright')
explode = [0, 0.05]
plt.pie(hd, labels = ['absence', 'presence'], autopct = '%0.0f%%', colors = clrs, explode = explode)
plt.title('Heart Diseases Population by percentage')
plt.show()

"""### OBSERVATION
- From the above Pie Chart, people not having heart disease (51%) are more than the people who have heart disease (49%)
"""

# Finding the minimum, maximum and average of the population age using statistical analysis
min_age = df['age'].min()
max_age = df['age'].max()
mean_age = df['age'].mean()
print(f"The minimum age is {min_age}")
print(f"The maximum age is {max_age}")
print(f"The average age is {np.round(mean_age, 2)}")

# Dividing the population age in different categories
young_age = df[(df['age'] >= 29) & (df['age'] < 40)]
middle_age = df[(df['age'] >= 40) & (df['age'] < 55)]
old_age = df[(df['age'] > 55)]
print(f"Number of young age people = {len(young_age)}")
print(f'Number of middle age people = {len(middle_age)}')
print(f'Number of old age people = {len(old_age)}')

# PLotting a Bar plot for different categories of population age
category = ['young_age','middle_age','old_age']
_count = [len(young_age), len(middle_age), len(old_age)]
plt.bar(category, _count, color = ['green', 'blue','red'])
plt.title('Age Category')
plt.xlabel('Age Range')
plt.ylabel('Count')
plt.show()

"""### OBSERVATION
- From the above plot, we observed that old age population is more than the middle age and young age population. And there is least population of young age.
"""

# Converting population age into range of age
def age_range(row):
    if row >= 29 and row < 40:
        return 'youngAge'
    elif row >= 40 and row < 55:
        return 'middleAge'
    else:
        return 'oldAge'

df['ageRange'] = df['age'].apply(age_range)
df.head()

# Converting numerical data into categorical data for sex
def _sex(row):
    if row == 1:
        return 'male'
    else:
        return 'female'

df['gender'] = df['sex'].apply(_sex)
df.head()

# Plotting a bar plot for Age category vs gender
sb.barplot(x = 'ageRange', y = 'age', hue = 'gender', ci = None, data = df)
plt.xlabel('Age Category')
plt.ylabel('Age')
plt.title('Bar Plot of Age Category vs Gender')
plt.show()

"""### OBSERVATION
- In the middle age, the number of male population is almost equal to the female population. In young age and old age female population is slightly more.
"""

# Plotting Count plot for heart diseases according to thier age category
plt.figure(figsize = (12,8))
hue_orders = ['youngAge', 'middleAge', 'oldAge']
plt.title("Heart Disease by Age Category")
sb.countplot(x = 'heart_disease', hue = 'ageRange', data = df, hue_order = hue_orders, palette = 'bright')
plt.xlabel("Heart Disease")
plt.ylabel('Counts')
plt.show()

"""### OBSERVATION
- Old age people are most affected by the Heart disease and young age people are least affected.
"""

# Plotting Count plot for heart diseases based on sex
plt.figure(figsize = (12,8))
plt.title("Heart Disease by Sex", fontsize = 18)
sb.countplot(x = df['heart_disease'], hue = 'gender', data = df, palette = "bright")
plt.xlabel("Heart Disease")
plt.ylabel('Counts')
plt.show()

"""### OBSERVATION
- From the above graph, it is observed that there are more number of males affected by heart diseases in comparison to females.
"""

# Converting numerical data into categorical data by type of chest pain
def typePain(val):
  if val == 0: return 'typical angina'
  elif val == 1: return 'atypical angina'
  elif val == 2: return 'non-anginal'
  else: return 'asymptomatic'

# Creating a column for type of chest pain
df['chestPain'] = df['cp'].apply(typePain)
df.head()

# Count plot based on chest pain experienced
plt.figure(figsize = (12,8))
plt.title("Chest Pain Experienced", fontsize = 18)
sb.countplot(x = df['heart_disease'], hue = 'cp', data = df, palette = "bright")
plt.legend(labels = ['0-typical angina','1-atypical angina','2-non-anginal pain','3-asymptomatic'])
plt.xlabel("Heart Disease")
plt.ylabel('Counts')
plt.show()

"""### OBSERVATION
- It is observed that people having typical anginal chest pain have higher chance of heart diseases.
"""

# Plotting Count plot for chest pain based on gender
plt.figure(figsize = (10,7))
plt.title("Chest Pain by Sex", fontsize = 18)
sb.countplot(x = df['gender'], hue = 'cp', data = df, palette = 'bright')
plt.legend(labels = ['0-typical angina','1-atypical angina','2-non-anginal pain','3-asymptomatic'])
plt.xlabel('Sex', fontsize = 15)
plt.ylabel('Count')
plt.show()

"""### OBSERVATION
- It is observed that higher number of males are suffering from chest pain.
"""

# Plotting Count plot for chest pain vs age group
plt.figure(figsize = (10,7))
plt.title("Chest Pain by Age Group", fontsize = 18)
sb.countplot(x = df['ageRange'], hue = 'cp', data = df, palette = 'bright', order = ['youngAge', 'middleAge', 'oldAge'])
plt.legend(labels = ['0-typical angina','1-atypical angina','2-non-anginal pain','3-asymptomatic'])
plt.xlabel('Age Groups')
plt.ylabel('Count')
plt.show()

"""### OBSERVATION
- It seems that old age and middle age group have very high typical angina chest pain and non-anginal chest pain.
"""

# Plotting Bar graph for Restin blood pressure(trestbs) based on Heart Disease
plt.figure(figsize = (10,7))
plt.title('Blood Pressure by Heart Disease', fontsize = 18)
sb.barplot(x = 'heart_disease', y = 'trestbps', hue = 'gender', data = df, palette = 'bright')
plt.xlabel('Heart Disease')
plt.ylabel('Resting Blood Pressure')
plt.show()

"""### OBSERAVTION
- It is observed that slightly higher Resting Blood Pressue has the risk of heart disease specially in female.
"""

# Plotting Bar graph for Cholestrol level based on Heart Disease
plt.figure(figsize = (10,7))
plt.title('Cholestrol Level by Heart Disease', fontsize = 18)
sb.barplot(x = 'heart_disease', y = 'chol', hue = 'gender', data = df, palette = 'bright')
plt.xlabel('Heart Disease')
plt.ylabel('Cholestrol level')
plt.show()

"""### OBSERVATION
- Cholestrol level is more in females as compared to males and has a high risk of heart disease risk.
"""

# Plotting Line plot for blood pressue vs age
plt.figure(figsize = (10,7))
plt.title('Blood Pressure by Age', fontsize=18)
sb.lineplot(x = 'age', y = 'trestbps', data = df, palette = 'bright')
plt.xlabel('Age')
plt.ylabel('Blood Pressure in mmHg')
plt.show()

"""### OBSERVATION
- The blood pressure is normal from 30 to 50 and after 50 it increases gradually to age of 60. And after age of 60 it is fluctuating drastically.
"""

# Plotting Line plot for cholestrol level vs age
plt.figure(figsize = (10,7))
plt.title('Cholestrol Level by Age', fontsize = 18)
sb.lineplot(x = 'age', y = 'chol', data = df, color = 'green')
plt.xlabel('Age')
plt.ylabel('Cholestrol Level')
plt.show()

"""### OBSERVATION
- Cholestral level is increasing after the age of 40.
"""

# Plotting Line plot for ST depression vs age
plt.figure(figsize = (10,7))
plt.title('ST depression by Age', fontsize = 18)
sb.lineplot(x = 'age', y = 'oldpeak', data = df, color = 'red')
plt.xlabel('Age')
plt.ylabel('ST depression')
plt.show()

"""### OBSERVATION
- Depression level is quite high in the age group of 30 to 40 and 50 to 70. Whereas in 40 to 55 the depression level is quite stable.
"""

# PLotting Bar graph for ST Depression vs Heart diseases
plt.figure(figsize = (10,7))
plt.title('ST Depression by Heart diseases', fontsize = 18)
sb.barplot(x = 'heart_disease', y = 'oldpeak', hue = 'gender', data = df, palette = 'bright')
plt.xlabel('Heart Disease')
plt.ylabel('ST Depression')
plt.show()

"""### OBSERVATION
- High ST depression mean that the person have high chances of Heart diseases.
"""

# Plotting Bar graph for exercise induced Angina vs Heart diseases
plt.figure(figsize = (10,7))
plt.title('Exercise induced angina by Heart diseases', fontsize = 18)
sb.barplot(x = 'heart_disease', y = 'exang', hue = 'gender', data = df, palette = 'bright')
plt.xlabel('Heart Disease')
plt.ylabel('Exercise induced Angina')
plt.show()

"""### OBSERVATION
- Exercise induced angina increase the risk of heart disease in both male and female.
"""

# Exporting the final data for creating tableau dashboard
df.to_csv("my_data.csv", index = False)

"""### FINDINGS

1. **Data Overview:**
   - The dataset contains information about individuals and whether they have heart disease.
   - No missing values were found in the dataset.

2. **Population Distribution:**
   - Approximately 51% of the population does not have heart disease, while 49% have heart disease.

3. **Age Distribution:**
   - The minimum age observed is 29, the maximum is 77, and the average age is approximately 54.
   - The population is divided into three age categories: young age (29-39), middle age (40-54), and old age (55 and above).
   - The old age population is more than the middle age and young age population.

4. **Gender Distribution:**
   - There are slightly more males affected by heart disease compared to females.

5. **Chest Pain Analysis:**
   - Individuals experiencing typical anginal chest pain have a higher chance of heart disease.
   - More males are suffering from chest pain compared to females.
   - Old age and middle age groups have a higher incidence of typical anginal chest pain and non-anginal chest pain.

6. **Blood Pressure and Cholesterol Levels:**
   - Higher resting blood pressure and cholesterol levels are associated with a higher risk of heart disease.
   - Females tend to have higher cholesterol levels compared to males.

7. **Age-related Trends:**
   - Blood pressure remains normal from ages 30 to 50, then gradually increases until around age 60.
   - Cholesterol levels start increasing after the age of 40.

8. **ST Depression and Exercise-Induced Angina:**
   - Higher ST depression levels indicate a higher risk of heart disease.
   - Exercise-induced angina increases the risk of heart disease in both males and females.
"""